library(devtools)
library(tidyverse)

load_all()

# Load sample data

pd <- pd_json2pd(c(
  "data-raw/two_geoms.json",
  "data-raw/four_geoms.json",
  "data-raw/test_spray.json",
  "data-raw/test_spray_bw.json",
  "data-raw/Anon_pen_spray.json"
))

background_image <- png::readPNG("inst/extdata/feet_background.png")

pd |>
  pd_recreate_drawing(
    background_image = background_image,
    filename = "R_sandbox/drawing.png"
  )


pd |>
  filter(id == "Anon") |>
  pd_recreate_drawing(save_plot = FALSE)

# % Generated by roxygen2: do not edit by hand
# % Please edit documentation in R/pd_recreate.R
# \name{pd_recreate_drawing}
# \alias{pd_recreate_drawing}
# \title{Recreate Drawings from Coordinate Data}
# \usage{
# pd_recreate_drawing(
#   .data,
#   background_image = NULL,
#   save_plot = TRUE,
#   filename = "drawing\%03d.png"
# )
# }
# \arguments{
# \item{.data}{A data frame containing drawing data with required columns:
# `id` (unique identifier for each drawing),
# `p` (list column containing coordinate information),
# `s` (list column containing stroke information),
# `w` (canvas width), and
# `h` (canvas height).}

# \item{background_image}{Optional. Background image for the plot. Can be either:
# (1) a character string giving the file path to a PNG image (will be read
# with png::readPNG()), or (2) a numeric array (pre-processed raster array
# from png::readPNG()). Default is NULL (no background).}

# \item{save_plot}{Logical. If TRUE, saves the plot as a PNG file. If FALSE,
# returns a ggplot2 object. Default is TRUE.}

# \item{filename}{Character string specifying the output filename pattern.
# Must end with ".png" if save_plot is TRUE. Use sprintf-style formatting
# (e.g., "drawing%03d.png") for multiple drawings. Default is "drawing%03d.png".}
# }
# \value{
# If save_plot is TRUE, saves PNG file(s) and returns a message.
#   If save_plot is FALSE, returns a ggplot2 object.
# }
# \description{
# This function recreates drawings from a data frame containing coordinate and
# stroke information. It supports both pen and spray tool types and can save
# the output as PNG files or return a ggplot2 object.
# }
# \details{
# The function processes drawing data by:

# The function processes drawing data by:
# \itemize{
#   \item Validating required columns and data structure
#   \item Unnesting nested coordinate and stroke data
#   \item Reverting y-coordinates to match plotting conventions
#   \item Scaling brush widths to appropriate sizes
#   \item Handling pen and spray tools differently (spray adds jitter)
#   \item Creating faceted plots for multiple drawings
# }

# For spray tool data, the function recreates the spray effect by adding
# random jitter within the spray radius. Brush widths are scaled from
# the range 1-20 to 0.1-5 mm for plotting.
# }
# \section{Warnings}{

# The function will warn and prompt for confirmation when attempting to
# recreate more than 9 drawings due to potential performance issues.
# }

# \examples{
# \dontrun{
# # Recreate and save drawings
# pd_recreate_drawing(drawing_data)

# # Return plot object without saving
# plot <- pd_recreate_drawing(drawing_data, save_plot = FALSE)

# # Use custom filename and background
# pd_recreate_drawing(
#   drawing_data,
#   background_image = bg_img,
#   filename = "output\%03d.png"
# )
# }

# }
