#' Manage overlapping markings in pain drawings
#' 
#' This function will  overlapping markings/strokes in pain drawings by the chosen method. The method <chr> can be 'merge', 'split', 'adoptA' or 'adoptB'. 
#' 
#' The `method` parameter determines the way overlaps are managed:
#' * "merge" will create a union of pairwise overlapping markings -- note i) this will result in the first marking being extended as the union of the two and the second marking will be deleted, ii) any enclosed 'holes' generated by the union will be ignored and incorporated in the resulting marking.
#' * "split" will subtract the overlapping area from both markings and create a new marking representing the overlap -- not currently implemented!
#' * "adoptA" will retain the first of the markings unchanged, and subtract the overlap from the second marking -- not currently implemented!
#' * "adoptB" will retain the second of the markings unchanged, and subtract the overlap from the first marking -- not currently implemented!
#'
#' @param pd A valid pain drawing data structure -- see [pd_check] for details.
#' @param method A string -- eigher "merge", "split", "adoptA" or "adoptB" -- currently only "merge" is implemented
#'
#' @returns A valid pain drawing data structure
#'
#' @export
#' @examples
#' 
#' 
pd_geom_manage_overlaps <- function(pd, method="merge") {
  # This function will take a pd data structure and for each
  # individual pain drawing merge strokes.

  # Run data sanity check ... to be completed

  # check bounding box overlaps...
  # bbox_intersects <- does_bbox_intersect(df, strokes_i[p1], strokes_i[p2])

  pd <- pd |>
    dplyr::group_by(id) |>
    dplyr::group_modify(\(points_by_id, grp_vars) {
      manage_stroke_overlaps(points_by_id, method)
    }) |>
    dplyr::ungroup()

  return(pd)
}

manage_stroke_overlaps <- function(points, method="merge") {
  # This function takes a tibble of strokes ('points' from a single pain drawing)
  # and manages any overlapping strokes

  # Expect only a single unique id -- i.e. points data from one and just one pain drawing
  # if(length(unique(points$id))!=1) {points <- points |> dplyr::filter(id == points[1,'id'])}

  strokes_i <- unique(points$i) # Hold the actual identifier of the discrete strokes
  n_strokes <- length(strokes_i) # How many of them there are (this may change in the while loop)
  p1 <- 1 # pointer 1
  p2 <- 2 # pointer 2

  # If there are not at least two strokes - there can be no overlaps so just return
  if (n_strokes<2) {return(points)}

  # This function needs to investigate each combination of pairs of strokes for overlap
  # The order of the strokes is not important, thus the runtime will be O(½n²-½n) which
  # is half of the nxn matrix. We can represent these stroke combinations with a single
  # vector of n elements if we use two pointers to iterate the vector - we will simply id
  # the strokes by their index in the list-of-strokes (los) list

  while (p1 < n_strokes) {
    while (p2 <=n_strokes) {
      # We need to check length of strokes (number of coordinates) and decide what to
      # to do with lengths of 0, 1 and 2. 
      
      a <- points |> dplyr::filter(i==strokes_i[p1])
      b <- points |> dplyr::filter(i==strokes_i[p2])
      
      # Apparently, clipper (C+), which polyclip is based on, employes a cheap bounding box check -- so we dont need to
      intersection <- pd_polyclip(a, b, op = "intersection") 
      #intersection <- pd_polyclip(a, b, op = "union") # This is only to merge the body template
      they_overlap <- !purrr::is_empty(intersection) # TRUE or FALSE
      #they_overlap <- length(intersection)!=2 # TRUE or FALSE ..This is only to merge the body template
      
      
      if (they_overlap) {
        if (method=="merge") {
          # Replace p1 by the union of p1 and p2, delete p2, reset length of points and reset p2=p1+1
          merge_result <- pd_polyclip(a, b, op = "union") |> dplyr::filter(i==1) # When merging, we should get only 1 resulting polygon -- any additional polygons are holes!
          points <- points |>
            dplyr::filter(i != strokes_i[p1] & i!= strokes_i[p2]) |>
            dplyr::bind_rows(dplyr::tibble(i=strokes_i[p1], x=merge_result$x, y=merge_result$y)) 
          strokes_i <- strokes_i[-p2] # Remove p2 
          n_strokes <- n_strokes-1
          p2 <- p1+1

        } else if (method=="split") {
          # Replace p1 and p2 by subtracting their overlap, create a new stroke(s) from the overlap, reset length of points and reset p2=p1+1
          # split overlaps into separate (typically 3) distinct polygons

          ###### This needs to be fixed!! When splitting, the non-overlap part of A and/or B may be also be
          ###### split into multiple polygons -- consider two bars crossing each other...
          minus_resultA <- polyclip::polyclip(A = a, B = b, op = "minus")[[1]]
          minus_resultB <- polyclip::polyclip(A = b, B = a, op = "minus")[[1]]
          points <- points |>
            dplyr::group_by(i) |>
            dplyr::group_modify(\(stroke, grp_vars) {
              if(grp_vars == strokes_i[p1]) {
                tibble(x = minus_resultA$x, y = minus_resultA$y)
              } else if (grp_vars == strokes_i[p2]) {
                tibble(x = minus_resultB$x, y = minus_resultB$y)
              } 
            }) |>
            dplyr::ungroup()
          for(j in intersection) { # There may be more than one distinct overlap area
            new_i <- max(strokes_i)+1 # The new stroke should have a unique identifier
            points <- bind_rows(points, map_dfr(j, \(z) {z}) |> mutate(i=new_i))
            n_strokes <- n_strokes + 1
            strokes_i[n_strokes] <- new_i
          }
        } else if (method=="adoptA") {
          # Let the overlap become part of polygon A and subtract it from B
          # Replace B by subtracting the overlap 
          minus_result <- polyclip::polyclip(A = b, B = a, op = "minus")[[1]]
          points <- points |>
            dplyr::filter(i!= strokes_i[p2]) |>
            dplyr::bind_rows(dplyr::tibble(i=strokes_i[p2], x=minus_result$x, y=minus_result$y)) |>
            dplyr::arrange(i)
        } else if (method=="adoptB") {
          # Let the overlap become part of polygon B and subtract it from A
          # Replace A by subtracting the overlap 
          minus_result <- polyclip::polyclip(A = a, B = b, op = "minus")[[1]]
          points <- points |>
            dplyr::filter(i!= strokes_i[p1]) |>
            dplyr::bind_rows(dplyr::tibble(i=strokes_i[p1], x=minus_result$x, y=minus_result$y)) |>
            dplyr::arrange(i)
        }
      } else {
        p2 <- p2+1
      }
    }
    p1 <- p1+1 # Advance p1
    p2 <- p1+1 # Reset p2
  }
  return(points)
}