#' Load pain drawings from RedCap Pain Sketcher json data
#'
#' This function reads data generated by the RedCap module 'Pain Sketcher' and converts it
#' into a valid pain drawing data structure -- see [pd_check] for more details
#' 
#' The RedCap Pain Sketcher json data structure must adhere to these criteria:
#' * It should be a list of named elements with meta data about the pain drawing. This must include 'id' <chr> which is a unique pain drawing identifier and 's' which is a data frame, furthermore:
#' * The element 's' must be a data frame with marking/stroke data, where each line represents a separate marking/stroke and this must include a column 'i' which is a unique identifier within that pain drawing and 'p' which is a list, furthermore:
#' * The element 'p' must be list of <int> matrixes of dimensions \[1:n, 1:2\] representing x and y corrdinates (col-wise)
#' 
#' @param files A list or vector of strings which represent file paths
#'
#' @returns A pain drawing data structure: a list of three named tibbles 'drawings', 'strokes' and 'points'
#'
#' @export
#' @examples
#' pd_json2pd(list("/dir/file1.json", "/dir/file2.json"))
#' pd_json2pd(c("/dir/file1.json", "/dir/file2.json"))
pd_json2pd <- function(files) {
  
  if(!is.list(files) && is.character(files)) { files <- purrr::map(files, \(x) {x})} 

  for (j in 1:length(files)) {
    if (file.exists(files[[j]])) {
      files[[j]] <- c(file=files[[j]], jsonlite::fromJSON(files[[j]]))
    } else {
      warning(paste0("File ", files[[j]], " not found"))
    }
  }
 
  return(list(
    drawings = files |> purrr::map_dfr(\(le) {le |> purrr::discard_at("s")}),
    strokes = files |> purrr::map_dfr(\(le) {le |> purrr::keep_at(c("id", "s"))}) |> dplyr::mutate(s = s |> purrr::discard_at("p")) |> tidyr:::unnest(cols=c(s)),
    points  = files |> purrr::map_dfr(\(le) {dplyr::tibble(id=le$id, i=le$s$i, p=le$s$p)}) |> tidyr::unnest(cols=c(p)) |> dplyr::mutate(x = p[,1], y=p[,2]) |> dplyr::select(-p)
  ))
}
