#' Load pain drawings from RedCap Pain Sketcher json data
#'
#' This function reads data generated by the RedCap module 'Pain Sketcher' and converts it
#' into a valid pain drawing data structure -- see [pd_check_data] for more details
#' 
#' @details
#' 
#' The RedCap Pain Sketcher json data structure must adhere to these criteria:
#' * It should be a list of named elements with meta data about the pain drawing. This must include 'id' <chr> which is a unique pain drawing identifier and 's' which is a data frame, furthermore:
#' * The element 's' must be a data frame with marking/stroke data, where each line represents a separate marking/stroke and this must include a column 'i' which is a unique identifier within that pain drawing and 'p' which is a list, furthermore:
#' * The element 'p' must be list of <int> matrixes of dimensions \[1:n, 1:2\] representing x and y corrdinates (col-wise)
#' 
#' @param files A list or vector of strings which represent file paths
#'
#' @returns A pain drawing data structure: a tibble with columns `id`, `s` and `p` -- see [pd_check_data] for more details.
#'
#' @export
#' @examples
#' pd_json2pd("data-raw/four_geoms.json")
#' 
pd_json2pd <- function(f_name) {
  # Sanity check -- is f_name a string
  if(!is.character(f_name)) {return(data.frame())}
  # Sanity check -- more than one filename?
  if(length(f_name)>1) {
    result <- tibble::tibble()
    for(f in f_name) {
      result <- dplyr::bind_rows(result, pd_json2pd(f))
    }
    return(result)
  } 
  # Sanity check -- does such a file exist?
  if(!file.exists(f_name)) {return(data.frame())}

  # Get the file content as a simple string and check whether it is valid json
  content <- readLines(f_name)
  if(!jsonlite::validate(content)) {return(data.frame())}

  # ...only then, convert string in json format to R data object
  content <- jsonlite::fromJSON(content)

  # Build the result in three stages:
  # Make results a tibble with `f` as the file name and all the content of the json data structure, except `s`
  result <- tibble::tibble(f=f_name, content |> purrr::discard_at("s")  |> purrr::map_dfr(\(x) {x}))
  maxy <- result$h # This is to flip the y-axis values in result$p
  # First add a column onto the result tibble, which contains a list (length=1) of a data frame of `i,x,y`
  result$p <- content$s$p |> purrr::imap_dfr(\(q,i) {tibble::tibble(i,x=q[,1],y=maxy-q[,2])}) |> list()
  # Then add a column onto the result, which is a list (legnth=1) of a data frame with stroke info
  result$s <- content$s |> dplyr::select(-p) |> list()

  

  return(result)
}
