#' Manage overlapping markings in pain drawings
#' 
#' This function will  overlapping markings/strokes in pain drawings by the chosen method. The method <chr> can be 'merge', 'split', 'adoptA' or 'adoptB'. 
#' 
#' The `method` parameter determines the way overlaps are managed:
#' * "merge" will create a union of pairwise overlapping markings -- note i) this will result in the first marking being extended as the union of the two and the second marking will be deleted, ii) any enclosed 'holes' generated by the union will be ignored and incorporated in the resulting marking.
#' * "split" will subtract the overlapping area from both markings and create a new marking representing the overlap -- not currently implemented!
#' * "adoptA" will retain the first of the markings unchanged, and subtract the overlap from the second marking -- not currently implemented!
#' * "adoptB" will retain the second of the markings unchanged, and subtract the overlap from the first marking -- not currently implemented!
#'
#' @param pd A valid pain drawing data structure -- see [pd_check_data] for details.
#' @param method A string -- eigher "merge", "split", "adoptA" or "adoptB" -- currently only "merge" is implemented
#'
#' @returns A valid pain drawing data structure
#'
#' @export
#' @examples
#' pd_poly_cleanup(pd_demo_data[1,], delta=20) |> pd_poly_manage_overlaps()
#' 
pd_poly_manage_overlaps <- function(p, method="merge") {
  # This function takes a single row pain drawing (pd1) and manages any overlapping strokes

  p <- p |> # p is a list of data frames (of x,y,i)
    purrr::map(\(df, i_df) {
      if(!tibble::is_tibble(df)) {
        NA
      } else {
        # We have coordinates in the data frame, but how many strokes        
        if (length(unique(df$i))<2) {
          # There is only a single stroke in data frame - thus no overlaps
          df # ..so just stick with current data frame
        } else {
          # There are multiple strokes in data frame - check for overlaps in external function          
          loop_pairwise(df, method) # Handle the overlaps pairwise
        }
      }
    })
}

loop_pairwise <- function(df, method="merge") {
  i_strokes <- unique(df$i) # Hold the actual identifiers of the discrete strokes
  n_strokes <- length(i_strokes) # How many of them there are (this may change in the while loop)
  p1 <- 1 # pointer 1
  p2 <- 2 # pointer 2

  # These loops will iterate each combination of pairs of strokes for overlap - merging as we go
  # The order of the strokes is not important, thus the runtime will be O(½n²-½n) which
  # is half of the nxn matrix. We can represent these stroke combinations with a single
  # vector of n elements if we use two pointers to iterate the vector - we will simply id
  # the strokes by their index in the list-of-strokes (los) list
  
  while (p1 < n_strokes) { # Loop all polygons as the first polygon in pairwise comparison
    while (p2 <= n_strokes) { # ..for each, loop remaining polygons as the second polygon in pairwise comparison
      # print(
      #   paste0(
      #     "There are ",n_strokes," strokes. P1 is ",p1," and points to ", i_strokes[p1],". P2 is ",p2," and points to ", i_strokes[p2],". All remaining strokes are: ", paste0(i_strokes, collapse=",")
      #   )
      # )
      a <- df |> dplyr::filter(i==i_strokes[p1]) # coordinates of first polygon
      b <- df |> dplyr::filter(i==i_strokes[p2]) # coordinates of second polygon

      # The following will return a df of x and y polygon coordinates (one for each intersection)
      intersection <- pd_poly_clip(a, b, op = "intersection") 
      they_overlap <- nrow(intersection)>1 # TRUE or FALSE
      # print(
      #   paste0(
      #     "P1 and P2 overlap: ", they_overlap
      #   )
      # )


      if (they_overlap) {
        if (method=="merge") {
          # Replace p1 by the union of p1 and p2, delete p2, reset length of strokes and reset p2=p1+1
          merge_result <- pd_poly_clip(a, b, op = "union") |> 
            dplyr::filter(i==1) # Use only first polygon, the rest are holes
          df <- df |>
            dplyr::filter(i != i_strokes[p1] & i != i_strokes[p2]) |> # Remove p1 and p2 from pd1 points data frame
            dplyr::bind_rows(dplyr::tibble(i=i_strokes[p1], x=merge_result$x, y=merge_result$y)) # Add the merge result as p1 in the pd1 points data frame
          # print(paste0("Merged stroke ", i_strokes[p1] ," and ", i_strokes[p2] ," with ",nrow(a), " and ",nrow(b), " points respectively into a new strokes with ",df|>dplyr::filter(i==i_strokes[p1])|>nrow()," points"))
          i_strokes <- i_strokes[-p2] # Remove p2 from vector of stroke indices we are iterating          
          n_strokes <- n_strokes-1
          p2 <- p1+1
        } else {
          # The method is not 'merge', but something else (e.g. split) -- not yet implemented
        }
      } else { 
        # if the do not overlap just move to the next stroke polygon
        p2 <- p2+1
      }
    } # end of inner loop (p2)
    p1 <- p1+1 # Advance p1
    p2 <- p1+1 # Reset p2
  } # end of out loop (p1)
    
    return(df)
}

#' Get estimates of computation complexity (a proxy of execution time) for managing overlaps
#'
#' Managing overlaps depends on pair wise comparison of each stroke/marking within a pain drawing. This is computationally intensive at O(n²) -- specifically ½n²-½n 
#' 
#' Furthermore, managing overlaps requires looking for polygon overlaps and unions for each pain of strokes/markings. This is computationally intensive at (typically) O(n log n) 
#' 
#' Thus, 
#' 
#' * a pain drawing with 5 strokes of 20 vertices each, will potentially require 1476 cpu cycles
#' * a pain drawing with 5 strokes of 50 vertices each, will potentially require 4605 cpu cycles
#' * a pain drawing with 20 strokes of 20 vertices each, will potentially require 28035 cpu cycles
#' 
#' The purpose of this function is to allow users to estimate computatinal complexity for each pain drawing, and take appropriate action.
#' 
#' @param p
#'
#' @returns
#'
#' @export
#' @examples
pd_estimate_manage_overlap_time <- function(p) {
  
  n_points_in_pd <- p |> purrr::map_int(\(pd_df) {if(tibble::is_tibble(pd_df)) {nrow(pd_df)} else {0}}) # How many points in each pain drawing
  i <- p |> purrr::map_int(\(pd_df) {if(tibble::is_tibble(pd_df)) {max(pd_df$i)} else {0}}) # How many strokes in each pain drawing
  n <- ifelse(i>0 , as.integer(round(n_points_in_pd/i)), 0) # What is mean number of points per stroke in each pain drawing
  
  # The computational complexity of iterating all i strokes in a pain drawing, where the mean number of points in each stroke is n, is:
  # ½i²-½i * 2n*log(2n) -- the first part being from all combinations of strokes and the second part from identifying intersections
  
  o <- ((0.5*(i^2))-(0.5*i)) * 2*n*log(2*n)
  o[which(is.na(o))] <- 0
  
  return(o)
}
