#' Import RedCap PainDrawR JSON data
#'
#' Reads JSON files generated by the RedCap *PainDrawR* module and converts
#' them into a pain drawing data structure (see [pdr_check_data()]).
#'
#' Each input file is expected to contain a single pain drawing. Multiple files
#' can be provided and will be combined row-wise.
#'
#' @details
#' **Expected JSON structure**
#'
#' The input JSON must conform to the following structure:
#'
#' * A named list containing metadata for a single pain drawing, including:
#'   * `id` (character): unique drawing identifier
#'   * `s`: stroke data
#'
#' * `s` must be a data frame where each row represents a stroke and includes:
#'   * `i`: integer stroke identifier (unique within drawing)
#'   * `p`: list-column of coordinate matrices
#'
#' * Each element of `p` must be an integer matrix with two columns:
#'   * column 1: x-coordinates
#'   * column 2: y-coordinates
#'
#' **Transformation details**
#'
#' * Coordinates are converted into the internal `p` format (`i`, `x`, `y`)
#' * The y-axis is flipped using the drawing height (`h`) so that the origin
#'   matches the internal coordinate system
#' * Stroke metadata (`s`) and coordinates (`p`) are stored as list-columns
#'
#' **Failure handling**
#'
#' If any of the following conditions occur, an empty `data.frame()` is returned:
#' * `files` is not a character vector
#' * a file does not exist
#' * file contents are not valid JSON
#'
#' @param files Character vector (or list coercible to character) of file paths.
#'
#' @returns
#' A list representing a valid pain drawing data structure, or NA if parsing fails.
#'
#' @export
#'
#' @examples
#' # Load a single file
#'#' pdr_import_json(pdr_example("four_geoms.json"))
#'
#' # Load multiple files
#' pdr_import_json(pdr_example(c("two_geoms.json", "four_geoms.json")))
#'
#' # Plot imported data
#' pdr_import_json(pdr_demo_filepath_json_file_1) |>
#'   pdr_recreate_drawing()


pdr_import_json <- function(files) {
  # This file imports json output from the redcap module PainDrawR

  # Sanity check on `files`
  if (is.list(files)) {
    files <- files |> purrr::map_chr(\(element) {as.character(element)})
  }
  if(!is.character(files) || length(files)==0) {
    warning("No JSON files specified")
    return(list())
  }
  
  # Iterate files and parse data
  result <- list()
  for(f in files) {
    # Sanity check -- does such a file exist?
    if(!file.exists(f)) {
      warning(paste0("Non-exisiting JSON files specified: ",f))
      result <- result |> purrr::list_assign(list()) # Add empty element
    } else {
      # Sanity check -- is content valid json?
      content <- readLines(f)
      if(!jsonlite::validate(content)) {
        warning("File content could not be validated as JSON")
        result <- result |> purrr::list_assign(list()) # Add empty element
      } else {
        # We have valid json content - now parse and add to result
        tmp <- jsonlite::fromJSON(content)
        tmp$.file <- f # store the file name
        tmp$.points <- tmp$s$p # p is stored as list col in 's' so move up a level..
        tmp$.strokes <- tmp$s |> dplyr::select(-p) |> tibble::as_tibble() # ..and remove from s
        tmp$.points <- tmp$.points |> purrr::imap_dfr(\(element, indx) {tibble::tibble(i=indx, x=element[,1], y=element[,2])})
        tmp$.id = tmp$id
        tmp$.file = tmp$file
        tmp$.version = tmp$v
        tmp$.width = tmp$w
        tmp$.height = tmp$h
        tmp$.units = tmp$coord
        tmp$.timestamp = tmp$ts
        tmp$.app = tmp$app
        tmp <- tmp[startsWith(names(tmp), ".")]
        tmp$.points <- tmp$.points |> dplyr::rename(.index=i, .x=x, .y=y)
        tmp$.strokes <- tmp$.strokes |> dplyr::rename(.index=i, .q=q, .tool=t, .tool_width=bw, .color=c, .alpha=a)
        result <- c(result , list(tmp))
      }
    }
  }
  return(result)
}
