#' Import RedCap PainDrawR JSON data
#'
#' Reads JSON files generated by the RedCap *PainDrawR* module and converts
#' them into a pain drawing data structure (see [pdr_check_data()]).
#'
#' Each input file is expected to contain a single pain drawing. Multiple files
#' can be provided and will be combined row-wise.
#'
#' @details
#' **Expected JSON structure**
#'
#' The input JSON must conform to the following structure:
#'
#' * A named list containing metadata for a single pain drawing, including:
#'   * `id` (character): unique drawing identifier
#'   * `s`: stroke data
#'
#' * `s` must be a data frame where each row represents a stroke and includes:
#'   * `i`: integer stroke identifier (unique within drawing)
#'   * `p`: list-column of coordinate matrices
#'
#' * Each element of `p` must be an integer matrix with two columns:
#'   * column 1: x-coordinates
#'   * column 2: y-coordinates
#'
#' **Transformation details**
#'
#' * Coordinates are converted into the internal `p` format (`i`, `x`, `y`)
#' * The y-axis is flipped using the drawing height (`h`) so that the origin
#'   matches the internal coordinate system
#' * Stroke metadata (`s`) and coordinates (`p`) are stored as list-columns
#'
#' **Failure handling**
#'
#' If any of the following conditions occur, an empty `data.frame()` is returned:
#' * `files` is not a character vector
#' * a file does not exist
#' * file contents are not valid JSON
#'
#' @param files Character vector (or list coercible to character) of file paths.
#'
#' @returns
#' A list representing a valid pain drawing data structure, or NA if parsing fails.
#'
#' @export
#'
#' @examples
#' # Load a single file
#'#' pdr_import_json(pdr_example("four_geoms.json"))
#'
#' # Load multiple files
#' pdr_import_json(pdr_example(c("two_geoms.json", "four_geoms.json")))
#'
#' # Plot imported data
#' pdr_import_json(pdr_demo_filepath_json_file_1) |>
#'   pdr_recreate_drawing()


pdr_import_json <- function(files) {
  if (is.list(files)) {
    files <- files |> purrr::map_chr(\(element) {as.character(element)})
  }
  # Sanity check -- is files a string
  if(!is.character(files)) {
    warning("No JSON files specified")
    return(tibble::tibble())
  }
  # Sanity check -- more than one filename?
  if(length(files)>1) {
    result <- tibble::tibble()
    for(f in files) {
      result <- dplyr::bind_rows(result, pdr_import_json(f))
    }
    return(result)
  } 
  # Sanity check -- does such a file exist?
  if(!file.exists(files)) {
    warning("Non-exisiting JSON files specified")
    return(tibble::tibble())
  }

  # Get the file content as a simple string and check whether it is valid json
  content <- readLines(files)
  if(!jsonlite::validate(content)) {
    warning("File content could not be validated as JSON")
    return(NA)
  }

  # ...only then, convert string in json format to R data object
  content <- jsonlite::fromJSON(content)

  # Build the result in three stages:
  # Make results a tibble with `f` as the file name and all the content of the json data structure, except `s`
  result <- tibble::tibble(f=files, content |> purrr::discard_at("s")  |> purrr::map_dfr(\(x) {x}))
  maxy <- result$h # This is to flip the y-axis values in result$p
  # First add a column onto the result tibble, which contains a list (length=1) of a data frame of `i,x,y`
  result$p <- content$s$p |> purrr::imap_dfr(\(q,i) {tibble::tibble(i,x=q[,1],y=maxy-q[,2])}) |> list()
  # Then add a column onto the result, which is a list (legnth=1) of a data frame with stroke info
  result$s <- content$s |> dplyr::select(-p) |> tibble::tibble() |> list()  
  # Now transpose the whole thing into a list of lists
  result <- purrr::transpose(result)

  return(result)
}
